<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class DivisiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('divisi')->insert([
            [
                'nama' => 'BAGIAN PENGENDALI ANAK PERUSAHAAN',
                'kode' => '5900',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'BAGIAN SISTEM MANAJEMEN INFORMASI',
                'kode' => '4400',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIREKSI',
                'kode' => '1000',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI AKUNTANSI KEUANGAN',
                'kode' => '3100',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI KEAMANAN',
                'kode' => '5100',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI MANAJEMEN OPERASIONAL',
                'kode' => '4300',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI PEMASARAN & PELAYANAN',
                'kode' => '4100',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI PERENCANAAN & PENGAWASAN',
                'kode' => '4200',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'DIVISI SUMBER DAYA MANUSIA & UMUM',
                'kode' => '3200',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'KOORDINATOR KSO',
                'kode' => '5500',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PKBL',
                'kode' => '3010',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PT. MARUNDA BANDAR INDONESIA',
                'kode' => '5800',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PT. KBN GRAHA MEDIKA',
                'kode' => '5700',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SATUAN PENGAWASAN INETRN',
                'kode' => '2100',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SBU KAWASAN TAKALAR',
                'kode' => '5910',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SBU PENGELOLAAN AIR',
                'kode' => '5020',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SBU PUSAT LOGISTIK BERIKAT',
                'kode' => '5090',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SEKRETARIAT PERUSAHAAN',
                'kode' => '2200',
                'unit_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'AKT & KEU SBU CAKUNG',
                'kode' => '5201',
                'unit_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'KEAMANAN SBU CAKUNG',
                'kode' => '5101',
                'unit_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'P INDUSTRI SBU CAKUNG',
                'kode' => '5202',
                'unit_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PEL. KAWASAN SBU CAKUNG',
                'kode' => '5204',
                'unit_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SDM & UMUM SBU CAKUNG',
                'kode' => '5203',
                'unit_id' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'AKT & KUE SBU PRIMA',
                'kode' => '5306',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'P INDUSTRI SBU PRIMA',
                'kode' => '5301',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PEL KAWASAN SBU PRIMA',
                'kode' => '5304',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SBU KAWASAN MARUNDA & TG.PRIOK',
                'kode' => '5300',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SBU PRIMA BETON NUSANTARA',
                'kode' => '5070',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SDM & UMUM SBU PRIMA',
                'kode' => '5302',
                'unit_id' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'AKT & KUE SBU LOGISTIK',
                'kode' => '5404',
                'unit_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'FORWARDING SBU LOGISTIK',
                'kode' => '5402',
                'unit_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'MANAGER SBU LOGISTIK',
                'kode' => '5401',
                'unit_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'PERGUDANGAN SBU LOGISTIK',
                'kode' => '5403',
                'unit_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'SDM & UMUM SBU LOGISTIK',
                'kode' => '5405',
                'unit_id' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'BURUH KEBERSIHAN PRIMA',
                'kode' => '6006',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'CLEANING SERVICE PRIMA',
                'kode' => '6001',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'CLEANING SERVICE PUSAT',
                'kode' => '6002',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'OPERASIONAL BONGKAR MUAT/PLB',
                'kode' => '6018',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'OPERASIONAL SBUK PRIMA',
                'kode' => '6022',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'RESEPSIONIS KBN PUSAT',
                'kode' => '6023',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'TEK/LAB KEBERSIHAN PRIMA BETON',
                'kode' => '6025',
                'unit_id' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'KOPERASI KARYAWAN',
                'kode' => '6000',
                'unit_id' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nama' => 'STAFF KHUSUS KOPERASI',
                'kode' => '6007',
                'unit_id' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
